Repository ShinhanT3-CardProject/Frontend-repo, pull requests merged in 2024-09, with the labels that each got.

#73 🌟(#13 ) [Fix] contribution 업데이트 로직 변경
  src/component/raid/RaidBattle.jsx
Labels: 🛠️fix

#74 🌟(#12)[Fix] 버킷리스트 한글해석
  src/component/theme/ThemeBucketList.jsx
Labels: 🛠️fix

#75 🌟[Fix] 홈페이지 배너 수정
  src/asset/css/carousel.css
  src/component/common/Home.jsx
  src/component/theme/ThemeList.jsx
Labels: 🎨design, 🛠️fix

#77 🌟(#12) [Feat] 로딩중 미니게임, 추천결과 키워드 볼드처리
  src/asset/css/LoadingGame.css
  src/asset/css/ThemeResultPage.css
  src/asset/css/bucketList.css
  src/asset/image/hitEffect.png
  src/asset/image/paper.jpg
  src/component/theme/LoadingGame.jsx
  src/component/theme/ThemeAnalyzeResult.jsx
  src/component/theme/ThemeBucketList.jsx
  src/index.js
Labels: 🎨design, 🌟feature

#78 🌟(#4 ) [Fix] panelControl(sidebar) 수정
  src/App.js
  src/asset/css/nav.css
  src/component/common/NavBar.jsx
  src/component/common/PanelControl.jsx
  src/component/coupon/CouponMain.jsx
Labels: 🛠️fix

#79 [Fix] 내정보 글자 색 수정
  src/asset/css/home.css
  src/asset/css/raidBattle.css
Labels: 🛠️fix

#82 🌟[Feat] Dockerfile & nginx 설정파일 추가
  Dockerfile
  conf/conf.d/default.conf
Labels: 🌟feature

#83 🌟[Feat] Dockerfile & nginx 설정파일 추가
  Dockerfile
  conf/conf.d/default.conf
Labels: 🌟feature

#87 🌟[Fix]Update docker-image.yml
  .github/workflows/docker-image.yml
Labels: 🐞bugfix

#88 🌟[Fix]Update docker-image.yml
  .github/workflows/docker-image.yml
Labels: 🐞bugfix

#89 [Feat][Fix] 테마 전체 조회 페이징, 테마 필터링 및 검색
  src/component/common/PanelControl.jsx
  src/component/theme/ThemeSearchMain.jsx
Labels: 🌟feature, 🛠️fix

#96 🌟[Fix] git action 조건
  .github/workflows/docker-image.yml
Labels: 🐞bugfix

#97 🌟[Fix] git action 조건
  .github/workflows/docker-image.yml
Labels: 🐞bugfix

#98 🌟[Feat] Backend 배포 주소 연결
  .github/workflows/docker-image.yml
  Dockerfile
  conf/conf.d/default.conf
  package.json
Labels: 🌟feature

#99 🌟[Feat] Backend 배포 주소 연결
  conf/conf.d/default.conf
  package.json
Labels: 🌟feature

#100 🌟(#6) [Fix] pagination 버튼 수정 (추가수정 아직 더 필요)
  src/asset/css/theme.css
  src/component/theme/ThemeSearchMain.jsx
Labels: 🛠️fix

#101 🌟(#6) [Fix] pagination 버튼 수정 (추가수정 아직 더 필요)
  src/asset/css/theme.css
  src/component/theme/ThemeSearchMain.jsx
Labels: 🛠️fix

#102 🌟[Feat] domain sever 설정
  conf/conf.d/default.conf
Labels: 🌟feature

#103 🌟[Feat] domain sever 설정
  conf/conf.d/default.conf
Labels: 🌟feature

#104 🌟(#12) [Feat] 테마 불러오기 기능, 버킷리스트 튜토리얼
  package-lock.json
  package.json
  src/asset/css/ThemeResultPage.css
  src/asset/css/bucketListStart.css
  src/asset/css/theme.css
  src/asset/image/airobot.png
  src/asset/image/writeNote.png
  src/component/theme/BucketListStart.jsx
  src/component/theme/ThemeDetail.jsx
Labels: 🎨design, 🌟feature, 🛠️fix

#106 🌟(#5) [Feat]카드목록, 사용내역 css 수정
  src/asset/css/cardlist.css
  src/asset/css/cardusagehistory.css
  src/component/card/CardList.jsx
  src/component/card/CardRecommend.jsx
  src/component/card/CardUsageHistory.jsx
Labels: 🌟feature

#107 🌟(#6) [Fix] themeSearchMain pagination 버튼 오류 1차 수정
  src/component/theme/ThemeSearchMain.jsx
Labels: 🐞bugfix

#109 🌟(#12) [Fix] alert창 변경 및 스탬프 해상도 조정
  package-lock.json
  package.json
  src/asset/css/StampBoard.css
  src/asset/css/ThemeResultPage.css
  src/asset/css/bucketListStart.css
  src/asset/css/theme.css
  src/asset/image/airobot.png
  src/asset/image/writeNote.png
  src/component/theme/BucketListStart.jsx
  src/component/theme/MyThemeDetail.jsx
  src/component/theme/ThemeDetail.jsx
  src/component/theme/ThemeRegister.jsx
Labels: 🐞bugfix, 🛠️fix

#105 🌟(#4 ) [Feat] 테마 랜덤포인트 모달
  src/asset/css/bannerTitle.png
  src/asset/css/theme.css
  src/component/point/PointMain.jsx
  src/component/theme/MyThemeDetail.jsx
Labels: 🌟feature, 🛠️fix

#113 🌟(#4) [Fix] 포인트 수정 추가
  src/component/theme/MyThemeDetail.jsx
Labels: 🛠️fix

#114 🌟(#13 ) [Fix] 레이드 체력 0 되면 이미지 사라짐
  src/component/raid/RaidBattle.jsx
Labels: 🛠️fix
