Repository ShinhanT3-CardProject/Frontend-repo, pull requests merged in 2024-08, with the labels that each got.

#3 🌟(#2) [Feat] 레이드리스트 kakao map api 연결
  .github/ISSUE_TEMPLATE/issue--🌟feature.md
  .github/ISSUE_TEMPLATE/issue--🐞bugfix.md
  .github/ISSUE_TEMPLATE/issue--💯test.md
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/index.js
  src/raid/RaidMap.jsx
Labels: 🌟feature

#11 🌟(#4 ) 부트스트랩 수정
  .gitignore
  env
  jsconfig.json
  package-lock.json
  package.json
  public/calendar.html
  public/carousel.html
  public/faq.html
  src/asset/css/font-awesome.min.css
  src/asset/css/materialize.min.css
  src/asset/css/owl.carousel.css
  src/asset/css/owl.theme.css
  src/asset/fonts/FontAwesome.otf
  src/asset/fonts/ajax-loader.gif
  src/asset/fonts/fontawesome-webfont.eot
  src/asset/fonts/fontawesome-webfont.svg
  src/asset/fonts/fontawesome-webfont.ttf
  src/asset/fonts/fontawesome-webfont.woff
  src/asset/fonts/fontawesome-webfont.woff2
  src/asset/fonts/slick.eot
  src/asset/fonts/slick.svg
  src/asset/fonts/slick.ttf
  src/asset/fonts/slick.woff
  src/component/RaidMap.jsx
  src/component/point/PointMain.jsx
  src/index.js
Labels: 🛠️fix

#18 Feat couponpage
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/asset/css/materialize.min.css
  src/asset/css/point.css
  src/asset/css/style.css
  src/asset/image/completeIcon.png
  src/asset/js/jquery.filterizr.min.js
  src/asset/js/jquery.min.js
  src/asset/js/materialize.min.js
  src/asset/js/owl.carousel.min.js
  src/asset/js/slick.min.js
  src/component/common/NavBar.jsx
  src/component/common/PanelControl.jsx
  src/component/coupon/CouponMain.jsx
  src/component/point/PointMain.jsx
  src/component/point/TransferComplete.jsx
  src/index.js
Labels: 🛠️fix

#20 🌟(#6) [Feat] theme.css 추가, component에 theme폴더, 테마 조회, 상세, 등록 페이지 추가
  src/asset/css/theme.css
  src/component/theme/MyThemeDetail.jsx
  src/component/theme/MyThemeSearch.jsx
  src/component/theme/ThemeDetail.jsx
  src/component/theme/ThemeRegister.jsx
  src/component/theme/ThemeSearchMain.jsx
  src/index.js
Labels: 🌟feature

#22 🌟(#2) [feat] 레이드 상세 모달 구현
  package-lock.json
  package.json
  src/component/raid/RaidMap.jsx
  src/component/raid/SearchRaid.jsx
  src/index.js
Labels: 🌟feature

#23 [Feat] 레이드 화면 구현 초안
  package-lock.json
  src/asset/css/raidBattle.css
  src/asset/image/raidBackground.jpg
  src/asset/sound/attack.mp3
  src/asset/sound/critical.mp3
  src/asset/sound/criticalhit.mp3
  src/asset/sound/miss.mp3
  src/component/raid/DiceRoll.jsx
  src/component/raid/RaidBattle.jsx
  src/index.js
Labels: 🌟feature

#24 🌟(#2) [Feat] 로그인 & 회원가입
  src/component/auth/Login.jsx
  src/component/auth/Registration.jsx
  src/component/common/Home.jsx
  src/index.js
Labels: 🌟feature

#25 🌟(#17 ) [Fix] sidenav 수정, point,coupon 페이지 수정
  src/App.css
  src/App.js
  src/asset/css/materialize.min.css
  src/asset/css/point.css
  src/component/common/NavBar.jsx
  src/component/common/PanelControl.jsx
  src/component/coupon/CouponMain.jsx
  src/component/point/PointMain.jsx
  src/component/point/PointTransfer.jsx
  src/component/point/TransferComplete.jsx
  src/component/theme/MyThemeDetail.jsx
  src/index.js
Labels: 🛠️fix

#28 🌟(#2) [Feat] 레이드 목록 출력 & 검색 기능 추가
  package-lock.json
  package.json
  src/component/raid/MainTest.jsx
  src/component/raid/RaidMap.jsx
  src/component/raid/RaidModal.jsx
  src/component/raid/SearchRaid.jsx
  src/index.js
Labels: 🌟feature

#33 🌟(#12) 테마 대분류 추천페이지 제작 및 스탬프 보드 일부 디자인
  package-lock.json
  src/asset/css/LoadingSpinner.css
  src/asset/css/StampBoard.css
  src/asset/css/ThemeResultPage.css
  src/asset/css/bucketList.css
  src/asset/js/api.js
  src/component/theme/LoadingSpinner.jsx
  src/component/theme/StampBoard.jsx
  src/component/theme/ThemeAnalyzeResult.jsx
  src/component/theme/ThemeBucketList.jsx
  src/index.js
Labels: 🎨design, 🌟feature

#31 🌟(#2) [Feat] 시도구 필터 추가
  package-lock.json
  package.json
  src/component/common/PanelControl.jsx
  src/component/raid/MainTest.jsx
  src/component/raid/RaidMap.jsx
  src/component/raid/SearchRaid.jsx
  src/index.js
Labels: 🌟feature

#34 🌟(#12) [Fix] 이미지 경로 수정
  src/asset/image/culture.jpg
  src/asset/image/dining.jpg
  src/asset/image/life.jpg
  src/asset/image/shopping.jpg
  src/asset/image/travel.jpg
  src/asset/sound/attack.mp3
  src/asset/sound/critical.mp3
  src/asset/sound/criticalhit.mp3
  src/asset/sound/miss.mp3
  src/component/theme/StampBoard.jsx
Labels: 🐞bugfix

#37 🌟(#13) [Feat] 배틀 화면 구현
  src/asset/css/raidBattle.css
  src/component/raid/DiceRoll.jsx
  src/component/raid/RaidBattle.jsx
Labels: 🌟feature

#38 🌟(#12) [Fix] 스탬프보드, 버킷리스트 결과 디자인 1차 수정 및 소분류 테마 값 넘겨주기
  src/asset/css/StampBoard.css
  src/asset/css/ThemeResultPage.css
  src/asset/css/bucketList.css
  src/asset/css/bucketListStart.css
  src/asset/css/theme.css
  src/asset/image/paper.jpg
  src/component/theme/BucketListStart.jsx
  src/component/theme/StampBoard.jsx
  src/component/theme/ThemeAnalyzeResult.jsx
  src/component/theme/ThemeRegister.jsx
  src/index.js
Labels: 🎨design, 🌟feature

#36 🌟(#5) [Feat][Fix] 결제내역
  src/asset/css/cardlist.css
  src/asset/css/cardusagehistory.css
  src/component/card/CardList.jsx
  src/component/card/CardUsageHistory.jsx
Labels: 🌟feature, 🛠️fix

#42 🌟(#13) [Feat] 레이드 화면 체력 바와 공격 로그 풀링 구현
  src/asset/css/raidBattle.css
  src/component/raid/RaidBattle.jsx
  src/index.js
Labels: 🌟feature

#43 🌟(#2) [Feat]레이드 참여내역 조회 구현
  public/index.html
  src/asset/css/RaidHistory.css
  src/component/raid/HistoryCard.jsx
  src/component/raid/RaidHistory.jsx
  src/component/raid/SearchRaid.jsx
  src/index.js
Labels: 🎨design, 🌟feature

#45 🌟(#5) [Fix] 카드사용내역, 카드목록
  src/asset/css/cardlist.css
  src/asset/css/cardusagehistory.css
  src/component/card/CardList.jsx
  src/component/card/CardUsageHistory.jsx
  src/component/common/PanelControl.jsx
  src/index.js
Labels: 🛠️fix

#41 🌟(#4) [Feat] 포인트 페이지 DB 연결
  src/component/point/PointMain.jsx
  src/component/point/PointTransfer.jsx
  src/component/point/TransferComplete.jsx
Labels: 🌟feature

#44 🌟(#6) [Feat] themeSearchMain 페이지 백엔드 연결 및 디자인 보완, themeDetail 보완
  src/asset/css/theme.css
  src/asset/image/cultureImage.jpg
  src/asset/image/dailyLifeImage.jpg
  src/asset/image/diningImage.jpg
  src/asset/image/shoppingImage.jpg
  src/asset/image/travelImage.jpg
  src/component/theme/StampBoard.jsx
  src/component/theme/ThemeDetail.jsx
  src/component/theme/ThemeRegister.jsx
  src/component/theme/ThemeSearchMain.jsx
  src/index.js
Labels: 🌟feature

#40 🌟(#1) 로그인 시 헤더변경및 메인화면 아이콘 경로 설정
  src/component/auth/Login.jsx
  src/component/common/Home.jsx
  src/component/common/NavBar.jsx
Labels: 🌟feature

#47 (#17 ) [Fix] 포인트/쿠폰 페이지 세션 아이디 가져오기
  src/asset/css/coupon.css
  src/asset/css/point.css
  src/component/coupon/CouponMain.jsx
  src/component/point/PointMain.jsx
  src/component/point/PointTransfer.jsx
  src/component/point/TransferComplete.jsx
  src/index.js
Labels: 🛠️fix

#49 [Design] 레이드 참여내역 css 수정
  src/asset/css/RaidHistory.css
  src/asset/css/style.css
  src/component/raid/HistoryCard.jsx
  src/component/raid/RaidHistory.jsx
Labels: 🎨design

#48 [Feat][Fix] 레이드 정보 추가 및 디자인 수정
  src/asset/css/raidBattle.css
  src/component/raid/RaidBattle.jsx
Labels: 🌟feature, 🛠️fix

#50 🌟(#6) [Feat] 테마 검색기능 및 필터검색 추가, 테마 수정기능 구현 중
  src/asset/css/theme.css
  src/component/theme/MyThemeDetail.jsx
  src/component/theme/MyThemeSearch.jsx
  src/component/theme/ThemeDetail.jsx
  src/component/theme/ThemeSearchMain.jsx
  src/index.js
Labels: 🌟feature

#51 🌟(#5) 카드추천, 카드목록
  src/asset/css/cardlist.css
  src/asset/css/cardrecommend.css
  src/component/card/CardList.jsx
  src/component/card/CardRecommend.jsx
  src/component/common/PanelControl.jsx
  src/index.js
Labels: 🎨design, 🌟feature

#52 🌟(#12) [Feat] 테마 등록하기 페이지
  src/asset/css/theme.css
  src/component/theme/StampBoard.jsx
  src/component/theme/ThemeAnalyzeResult.jsx
  src/component/theme/ThemeRegister.jsx
Labels: 🌟feature

#53 🌟(#12) [Fix] 버킷리스트 결과값 불러오기 오류 수정 및 추천결과 디자인 수정
  src/asset/css/ThemeResultPage.css
  src/component/theme/ThemeAnalyzeResult.jsx
  src/component/theme/ThemeRegister.jsx
  src/component/theme/ThemedBalloons.jsx
Labels: 🐞bugfix, 🎨design

#57 🌟(#13 ) [Fix] 전투 이미지 수정 및 조건별 몬스터 이미지 구현
  src/asset/css/raidBattle.css
  src/asset/image/king100.png
  src/asset/image/king25.png
  src/asset/image/king50.png
  src/asset/image/king75.png
  src/asset/image/raidBackground.jpg
  src/asset/image/slime100.png
  src/asset/image/slime25.png
  src/asset/image/slime50.png
  src/asset/image/slime75.png
  src/component/raid/RaidBattle.jsx
Labels: 🛠️fix

#55 🌟(#46) [Feat]레이드 검색&참여내역 상세 페이지 연결
  package-lock.json
  package.json
  src/App.css
  src/asset/css/RaidHistory.css
  src/component/raid/HistoryCard.jsx
  src/component/raid/RaidHistory.jsx
  src/component/raid/SearchRaid.jsx
Labels: 🌟feature

#56 🌟(#6) [Feat][Fix] MyThemeDetail 페이지 수정기능 추가 및 수정
  src/asset/css/theme.css
  src/component/theme/MyThemeDetail.jsx
  src/component/theme/ThemeDetail.jsx
  src/component/theme/ThemeRegister.jsx
Labels: 🌟feature, 🛠️fix

#54 🌟(#1) nav 및 헤더 수정
  src/App.js
  src/asset/css/home.css
  src/asset/css/nav.css
  src/asset/css/slider.css
  src/asset/image/login.png
  src/asset/image/logout.png
  src/component/auth/AuthContext.jsx
  src/component/auth/AuthProvider.jsx
  src/component/auth/Login.jsx
  src/component/common/Home.jsx
  src/component/common/NavBar.jsx
  src/component/common/PanelControl.jsx
  src/component/home/Services.jsx
  src/component/home/Slider.jsx
  src/component/home/SliderButton.jsx
Labels: 🎨design

#59 🌟(#5) [Feat]세션
  src/component/card/CardUsageHistory.jsx
  src/index.js
Labels: 🌟feature

#61 🌟(#13 ) [Fix] 버프 정보 추가
  src/component/raid/RaidBattle.jsx
Labels: 🛠️fix

#63 🌟(#46) [Feat] Main 페이지 구현
  package-lock.json
  package.json
  src/App.js
  src/asset/css/RaidHistory.css
  src/asset/css/RaidSearch.css
  src/asset/css/home.css
  src/asset/css/materialize.min.css
  src/asset/css/style.css
  src/asset/image/cardIcon.png
  src/asset/image/github.jpg
  src/component/common/Footer.jsx
  src/component/common/Home.jsx
  src/component/common/NavBar.jsx
  src/component/common/PanelControl.jsx
  src/component/home/Services.jsx
  src/component/home/Slider.jsx
  src/component/home/SliderButton.jsx
  src/component/raid/HistoryCard.jsx
  src/component/raid/MainTest.jsx
  src/component/raid/RaidHistory.jsx
  src/component/raid/RaidModal.jsx
  src/component/raid/SearchRaid.jsx
  src/component/theme/ThemeList.jsx
  src/index.js
Labels: 🎨design, 🌟feature

#62 🌟(#12) [fix] 테마 수정 화면에서 기존 테마 불러오기 일부 수정
  src/component/theme/MyThemeDetail.jsx
  src/component/theme/ThemeBucketList.jsx
  src/component/theme/ThemeRegister.jsx
Labels: 🛠️fix

#64 🌟(#12) [fix] 테마 등록 최대 3개까지 가능 정책 추가
  src/component/theme/MyThemeDetail.jsx
  src/component/theme/ThemeRegister.jsx
Labels: 🛠️fix

#65 🌟(#6) [Fix] theme stamp이미지 관련 로직 추가 (동작 스탬프, 테마 미션 출력으로 변경), 삭제시 alert 추가
  src/asset/css/StampBoard.css
  src/asset/css/theme.css
  src/asset/image/cultreIcon.png
  src/asset/image/diningIcon.png
  src/asset/image/lifestyleIcon.png
  src/asset/image/shoppingIcon2.png
  src/asset/image/travelcon.png
  src/component/theme/MyThemeDetail.jsx
  src/component/theme/StampBoard.jsx
  src/component/theme/ThemeDetail.jsx
  src/component/theme/ThemeRegister.jsx
Labels: 🛠️fix

#68 (#13 ) [[Fix] 레이드 정보 새로고침
  src/component/raid/RaidBattle.jsx
Labels: 🛠️fix

#71 🌟(#6) [Fix] myThemeDetail의 조회화면에서 스템프 찍기 구현
  src/asset/image/complete.png
  src/component/theme/MyThemeDetail.jsx
  src/component/theme/MyThemeSearch.jsx
  src/component/theme/ThemeDetail.jsx
  src/component/theme/ThemeList.jsx
  src/component/theme/ThemeSearchMain.jsx
Labels: 🛠️fix

#67 🌟(#4 ) 포인트 디자인 추가, toLocaleString 추가
  package-lock.json
  package.json
  src/asset/css/point.css
  src/component/point/PointMain.jsx
  src/component/point/PointTransfer.jsx
  src/component/point/TransferComplete.jsx
Labels: 🛠️fix

#72 🌟(#1) [Feat] navbar 클릭시 닫힘 기능
  src/App.js
  src/component/auth/AuthContext.jsx
  src/component/auth/AuthProvider.jsx
  src/component/common/Home.jsx
  src/component/common/NavBar.jsx
  src/component/common/PanelControl.jsx
  src/index.js
Labels: 🌟feature
